# -*- coding: utf-8 -*-
"""Clase5-Avanzado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vh1vzwedwj8Xcedy5LVnNDTuh6RWD9wL
"""

import ipywidgets as widgets
from IPython.display import display, HTML
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------------------------------------------------------
# 1. CARGA Y PREPARACIÓN DE DATOS MULTIAREA
# ------------------------------------------------------------------------------
df = pd.read_excel('Dataset_Integrado_Final_Sesion4.xlsx', sheet_name='Consolidado_Multiarea')
df['Fecha_Operacion'] = pd.to_datetime(df['Fecha_Operacion'])

# ------------------------------------------------------------------------------
# 2. SECCIÓN A: FILTROS GLOBALES DEL TABLERO
# ------------------------------------------------------------------------------
paises = ['Todos'] + sorted(df['Pais_Sede'].dropna().unique().tolist())
canales = ['Todos'] + sorted(df['Canal'].dropna().unique().tolist())
tiers = ['Todos'] + sorted(df['Tier_Estrategico'].dropna().unique().tolist())
estados = ['Todos'] + sorted(df['Estado_Cobranza'].dropna().unique().tolist())

filtro_pais = widgets.Dropdown(options=paises, value='Todos', description='País:', layout=widgets.Layout(width='24%'))
filtro_canal = widgets.Dropdown(options=canales, value='Todos', description='Canal:', layout=widgets.Layout(width='24%'))
filtro_tier = widgets.Dropdown(options=tiers, value='Todos', description='Tier:', layout=widgets.Layout(width='24%'))
filtro_estado = widgets.Dropdown(options=estados, value='Todos', description='Cobranza:', layout=widgets.Layout(width='24%'))

fila_filtros = widgets.HBox(
    [filtro_pais, filtro_canal, filtro_tier, filtro_estado],
    layout=widgets.Layout(margin='10px 0px 15px 0px', padding='12px', background_color='#F1F5F9', border='1px solid #CBD5E1', border_radius='8px')
)

# ------------------------------------------------------------------------------
# 3. SECCIÓN B: SELECTORES DEL CONSTRUCTOR DE TABLA DINÁMICA
# ------------------------------------------------------------------------------
opciones_filas = ['Sector_Industria', 'Pais_Sede', 'Ejecutivo_KAM', 'Canal', 'Metodo_Pago', 'Tier_Estrategico']
opciones_columnas = ['Estado_Cobranza', 'Tier_Estrategico', 'Canal', 'Pais_Sede']
opciones_metricas = [
    'Suma Facturación ($ USD)',
    'Suma Margen Neto ($ USD)',
    'Promedio Días de Mora',
    'Conteo de Transacciones'
]

pivot_fila = widgets.Dropdown(options=opciones_filas, value='Sector_Industria', description='Filas:', layout=widgets.Layout(width='32%'))
pivot_col = widgets.Dropdown(options=opciones_columnas, value='Estado_Cobranza', description='Columnas:', layout=widgets.Layout(width='32%'))
pivot_metrica = widgets.Dropdown(options=opciones_metricas, value='Suma Facturación ($ USD)', description='Métrica:', layout=widgets.Layout(width='32%'))

fila_pivot = widgets.HBox(
    [pivot_fila, pivot_col, pivot_metrica],
    layout=widgets.Layout(margin='10px 0px 20px 0px', padding='12px', background_color='#EEF2FF', border='1px solid #C7D2FE', border_radius='8px')
)

# ------------------------------------------------------------------------------
# 4. FUNCIÓN REACTIVA DEL DASHBOARD INTEGRAL
# ------------------------------------------------------------------------------
def render_dashboard_con_pivot(pais, canal, tier, estado, p_fila, p_col, p_metrica):
    # 1. Filtrado de datos
    dff = df.copy()
    if pais != 'Todos':
        dff = dff[dff['Pais_Sede'] == pais]
    if canal != 'Todos':
        dff = dff[dff['Canal'] == canal]
    if tier != 'Todos':
        dff = dff[dff['Tier_Estrategico'] == tier]
    if estado != 'Todos':
        dff = dff[dff['Estado_Cobranza'] == estado]

    if dff.empty:
        display(HTML("<div style='color:#EF4444; font-weight:bold; padding:20px; font-size:16px;'>⚠️ No hay transacciones que cumplan con la combinación de filtros seleccionada.</div>"))
        return

    # 2. Métricas y Tarjetas KPIs
    total_fact = dff['Monto_Facturado_USD'].sum()
    total_cobr = dff['Monto_Neto_Cobrado_USD'].sum()
    total_mora = dff[dff['Estado_Cobranza'] != 'Cobrado / Al Día']['Monto_Facturado_USD'].sum()
    margen_neto = dff['Margen_Operativo_USD'].sum()
    pct_mora = (total_mora / total_fact * 100) if total_fact > 0 else 0
    pct_cobrado = (total_cobr / total_fact * 100) if total_fact > 0 else 0
    margen_pct = (margen_neto / total_fact * 100) if total_fact > 0 else 0

    html_cards = f"""
    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 20px;">
        <div style="background: #FFFFFF; border: 1px solid #CBD5E1; border-top: 4px solid #1E3A8A; border-radius: 8px; padding: 12px 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <div style="font-size: 11px; color: #64748B; font-weight: 700; text-transform: uppercase;">Facturación Total</div>
            <div style="font-size: 22px; font-weight: 800; color: #0F172A; margin: 4px 0;">${total_fact:,.2f}</div>
            <div style="font-size: 11px; color: #64748B;">{len(dff)} transacciones</div>
        </div>
        <div style="background: #FFFFFF; border: 1px solid #CBD5E1; border-top: 4px solid #0D9488; border-radius: 8px; padding: 12px 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <div style="font-size: 11px; color: #64748B; font-weight: 700; text-transform: uppercase;">Cobrado Efectivo</div>
            <div style="font-size: 22px; font-weight: 800; color: #0D9488; margin: 4px 0;">${total_cobr:,.2f}</div>
            <div style="font-size: 11px; color: #0D9488; font-weight: 600;">{pct_cobrado:.1f}% efectividad</div>
        </div>
        <div style="background: #FFFFFF; border: 1px solid #CBD5E1; border-top: 4px solid #EF4444; border-radius: 8px; padding: 12px 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <div style="font-size: 11px; color: #64748B; font-weight: 700; text-transform: uppercase;">Cartera en Mora</div>
            <div style="font-size: 22px; font-weight: 800; color: #EF4444; margin: 4px 0;">${total_mora:,.2f}</div>
            <div style="font-size: 11px; color: #EF4444; font-weight: 600;">{pct_mora:.1f}% en riesgo</div>
        </div>
        <div style="background: #FFFFFF; border: 1px solid #CBD5E1; border-top: 4px solid #F59E0B; border-radius: 8px; padding: 12px 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <div style="font-size: 11px; color: #64748B; font-weight: 700; text-transform: uppercase;">Margen Operativo</div>
            <div style="font-size: 22px; font-weight: 800; color: #B45309; margin: 4px 0;">{margen_pct:.1f}%</div>
            <div style="font-size: 11px; color: #64748B;">${margen_neto:,.2f} neto</div>
        </div>
    </div>
    """
    display(HTML(html_cards))

    # 3. Gráficos Visuales 2x2
    fig, axs = plt.subplots(2, 2, figsize=(16, 9))
    fig.patch.set_facecolor('#FFFFFF')
    colores_cob = {'Cobrado / Al Día': '#10B981', 'Mora Leve (<30d)': '#F59E0B', 'Mora Crítica (>30d)': '#EF4444'}

    # [0, 0] Facturación por Sector y Cobranza
    df_sec = dff.groupby(['Sector_Industria', 'Estado_Cobranza'])['Monto_Facturado_USD'].sum().unstack().fillna(0)
    cols_exist = [c for c in ['Cobrado / Al Día', 'Mora Leve (<30d)', 'Mora Crítica (>30d)'] if c in df_sec.columns]
    df_sec = df_sec[cols_exist] if cols_exist else df_sec
    df_sec.plot(kind='bar', stacked=True, ax=axs[0, 0], color=[colores_cob.get(c, '#64748B') for c in df_sec.columns])
    axs[0, 0].set_title('1. Facturación por Sector Industrial y Cobro', fontweight='bold', fontsize=11, color='#0F172A')
    axs[0, 0].tick_params(axis='x', rotation=18)
    axs[0, 0].spines[['top', 'right']].set_visible(False)

    # [0, 1] Dona por Tier
    df_tier = dff.groupby('Tier_Estrategico')['Monto_Facturado_USD'].sum()
    axs[0, 1].pie(df_tier, labels=df_tier.index, autopct='%1.1f%%', colors=['#1E3A8A', '#0D9488', '#F59E0B'],
                  wedgeprops=dict(width=0.45, edgecolor='w'))
    axs[0, 1].set_title('2. Participación por Tier de Cliente', fontweight='bold', fontsize=11, color='#0F172A')

    # [1, 0] Días de Mora
    if len(dff) < 4:
        axs[1, 0].bar(dff['Sector_Industria'], dff['Dias_Mora'], color='#EF4444', width=0.35)
        axs[1, 0].set_ylabel('Días de Mora')
    else:
        sns.boxplot(data=dff, x='Sector_Industria', y='Dias_Mora', ax=axs[1, 0], palette='Blues')
        axs[1, 0].tick_params(axis='x', rotation=18)
    axs[1, 0].set_title('3. Auditoría de Mora por Sector', fontweight='bold', fontsize=11, color='#0F172A')
    axs[1, 0].spines[['top', 'right']].set_visible(False)

    # [1, 1] Cartera por KAM
    df_kam = dff.groupby('Ejecutivo_KAM')['Monto_Facturado_USD'].sum()
    axs[1, 1].barh(df_kam.index, df_kam.values / 1000, color='#0D9488', height=0.45)
    axs[1, 1].set_title('4. Cartera Total por KAM ($k USD)', fontweight='bold', fontsize=11, color='#0F172A')
    axs[1, 1].set_xlabel('Miles de USD ($k)')
    axs[1, 1].spines[['top', 'right']].set_visible(False)

    plt.tight_layout(pad=2.8)
    plt.show()

    # 4. CONSTRUCCIÓN DE LA TABLA DINÁMICA PERSONALIZADA (PIVOT TABLE)
    display(HTML(f"""
    <div style='margin-top: 25px; margin-bottom: 8px;'>
        <h3 style='color: #0F172A; margin: 0; font-family: sans-serif;'>📊 Tabla Dinámica: {p_fila} vs {p_col}</h3>
        <p style='color: #64748B; font-size: 13px; margin: 2px 0 10px 0;'>Métrica calculada: <b>{p_metrica}</b> con totales generales automáticos</p>
    </div>
    """))

    mapa_metricas = {
        'Suma Facturación ($ USD)': ('Monto_Facturado_USD', 'sum', '${:,.2f}'),
        'Suma Margen Neto ($ USD)': ('Margen_Operativo_USD', 'sum', '${:,.2f}'),
        'Promedio Días de Mora': ('Dias_Mora', 'mean', '{:.1f} días'),
        'Conteo de Transacciones': ('ID_Transaccion', 'count', '{:,.0f}')
    }
    col_valor, funcion_agg, formato_num = mapa_metricas[p_metrica]

    # Evitar error si el usuario elige el mismo campo en fila y columna
    if p_fila == p_col:
        display(HTML("<div style='color:#B45309; font-weight:bold; padding:10px;'>Selecciona campos distintos para 'Filas' y 'Columnas'.</div>"))
        return

    tabla_pivot = pd.pivot_table(
        dff,
        index=p_fila,
        columns=p_col,
        values=col_valor,
        aggfunc=funcion_agg,
        fill_value=0,
        margins=True,
        margins_name='Total General'
    )

    # Formateo estético estilo Excel Ejecutivo (Cabecera Azul Marino y Bordes)
    estilo_pivot = tabla_pivot.style.format(formato_num).set_table_styles([
        {'selector': 'th', 'props': [
            ('background-color', '#1E3A8A'),
            ('color', '#FFFFFF'),
            ('font-weight', 'bold'),
            ('text-align', 'center'),
            ('padding', '8px 14px'),
            ('border', '1px solid #CBD5E1')
        ]},
        {'selector': 'td', 'props': [
            ('text-align', 'right'),
            ('padding', '7px 14px'),
            ('border', '1px solid #E2E8F0'),
            ('font-family', 'sans-serif')
        ]},
        {'selector': 'tr:nth-child(even)', 'props': [('background-color', '#F8FAFC')]},
        {'selector': 'tr:hover', 'props': [('background-color', '#EEF2FF')]},
        {'selector': 'tr:last-child', 'props': [
            ('font-weight', 'bold'),
            ('background-color', '#E2E8F0'),
            ('border-top', '2px solid #0F172A')
        ]}
    ])

    display(estilo_pivot)

# ------------------------------------------------------------------------------
# 5. RENDERIZADO REACTIVO INTEGRADO
# ------------------------------------------------------------------------------
salida = widgets.interactive_output(
    render_dashboard_con_pivot,
    {
        'pais': filtro_pais, 'canal': filtro_canal, 'tier': filtro_tier, 'estado': filtro_estado,
        'p_fila': pivot_fila, 'p_col': pivot_col, 'p_metrica': pivot_metrica
    }
)

display(
    HTML("<h4 style='color:#1E3A8A; margin-bottom:4px;'>1. Filtros Globales del Portafolio:</h4>"),
    fila_filtros,
    HTML("<h4 style='color:#4338CA; margin-bottom:4px;'>2. Configuración de la Tabla Dinámica:</h4>"),
    fila_pivot,
    salida
)